---
name: release

on:
  create:
    tags:
      - '*'

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: |
          git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
